version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      next-js:
        patterns:
          - "next"
          - "eslint-config-next"
          - "react"
          - "react-dom"
      dev-dependencies:
        dependency-type: development
    ignore:
      - dependency-name: eslint
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
