import {
  fingerprintColorScale,
  fingerprintLegendStops,
  symmetricAbsMax,
  yearRangesInWindow,
  dayIndexTicks,
  formatDayTick,
  FINGERPRINT_HOUR_TICKS,
} from "@/lib/map/fingerprintScale";
import { dayIndexToUTCDate } from "@/lib/zarr/timeRange";
import { formatSeriesValue } from "@/components/map/timeSeriesChartConfig";
import type { ExportProvenance } from "./provenance";
import type { CapturedImage } from "./capture";

export type SquareLogoPreset = {
  id: string;
  label: string;
  size: number;
};

export const SQUARE_LOGO_PRESETS: readonly SquareLogoPreset[] = [
  { id: "sm", label: "Small (512 × 512)", size: 512 },
  { id: "md", label: "Medium (800 × 800)", size: 800 },
  { id: "lg", label: "Standard (1024 × 1024)", size: 1024 },
  { id: "xl", label: "High-Res (1200 × 1200)", size: 1200 },
  { id: "2xl", label: "Ultra (2048 × 2048)", size: 2048 },
] as const;

export const DEFAULT_SQUARE_LOGO_SIZE = 1024;

export type SquareFingerprintOptions = {
  values: Float32Array;
  prov: ExportProvenance;
  units?: string | null;
  absMax?: number;
  hoursPerDay?: number;
  size?: number;
  isLight?: boolean;
  watermarkText?: string;
  selectedYear?: number | null;
};

function formatCardinalCoord(lat: number, lon: number): string {
  const latStr = `${Math.abs(lat).toFixed(3)}° ${lat >= 0 ? "N" : "S"}`;
  const lonStr = `${Math.abs(lon).toFixed(3)}° ${lon >= 0 ? "E" : "W"}`;
  return `${latStr}, ${lonStr}`;
}

const MONO_FONT_FAMILY =
  'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace';
const SANS_FONT_FAMILY =
  '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';

/**
 * Builds a high-resolution, full-bleed square (1:1) vertical fingerprint graphic.
 *
 * Layout features:
 * - Full-bleed vertical heatmap filling the entire square (0,0 to size,size)
 * - If selectedYear is specified, isolates only that single calendar year
 * - Inward axis ticks: all year ticks when multi-year; month ticks when single-year
 * - Top-Left: Data source provenance badge with ample top and left padding
 * - Top-Right: Watermark "Generated by EarthPrints"
 * - Bottom-Left: Overlaid Origin Pixel geographic coordinates
 * - Bottom-Right: Overlaid Diverging Colorbar legend with min/max & units
 */
export function buildSquareFingerprintCanvas({
  values,
  prov,
  units = prov.units,
  absMax = symmetricAbsMax(values),
  hoursPerDay = prov.hoursPerDay || 24,
  size = DEFAULT_SQUARE_LOGO_SIZE,
  isLight = false,
  watermarkText = "Generated by EarthPrints",
  selectedYear = null,
}: SquareFingerprintOptions): HTMLCanvasElement {
  const canvas = document.createElement("canvas");
  canvas.width = size;
  canvas.height = size;

  const ctx = canvas.getContext("2d");
  if (!ctx) {
    throw new Error("Could not create 2D canvas context");
  }

  const s = size / 1024; // base scale factor relative to 1024px
  const nDaysFull = Math.floor(values.length / hoursPerDay);

  // Derive year ranges across the loaded record
  const allYears = yearRangesInWindow(prov.baseDay, nDaysFull);
  const activeYearRange =
    selectedYear !== null
      ? (allYears.find((r) => r.year === selectedYear) ?? null)
      : null;

  const dayLo = activeYearRange ? activeYearRange.startDay : 0;
  const dayHi = activeYearRange ? activeYearRange.endDay : nDaysFull - 1;
  const nDays = Math.max(1, dayHi - dayLo + 1);
  const baseDay = prov.baseDay + dayLo;

  // 1. Base background for transparent/missing gaps
  ctx.fillStyle = isLight ? "#ffffff" : "#0a0c10";
  ctx.fillRect(0, 0, size, size);

  // 2. Full-bleed Vertical Fingerprint Heatmap (X = hour 0..23, Y = day 0..nDays-1)
  if (nDays > 0) {
    const scale = fingerprintColorScale(isLight);
    const colW = size / hoursPerDay;

    for (let py = 0; py < size; py++) {
      const dayOffset = Math.min(nDays - 1, Math.floor((py / size) * nDays));
      const dayGlobal = dayLo + dayOffset;

      for (let hour = 0; hour < hoursPerDay; hour++) {
        const val = values[dayGlobal * hoursPerDay + hour] as number;
        const color = scale(val, absMax);
        if (color === "transparent") continue;

        const x0 = Math.floor(hour * colW);
        const x1 = Math.floor((hour + 1) * colW);
        ctx.fillStyle = color;
        ctx.fillRect(x0, py, Math.max(1, x1 - x0), 1);
      }
    }
  }

  // 3. Subtle Ambient Corner Scrim Gradients for contrast
  const scrimSize = Math.round(200 * s);

  // Top scrim
  const topGrad = ctx.createLinearGradient(0, 0, 0, scrimSize);
  topGrad.addColorStop(
    0,
    isLight ? "rgba(255, 255, 255, 0.80)" : "rgba(8, 10, 15, 0.80)",
  );
  topGrad.addColorStop(
    1,
    isLight ? "rgba(255, 255, 255, 0)" : "rgba(8, 10, 15, 0)",
  );
  ctx.fillStyle = topGrad;
  ctx.fillRect(0, 0, size, scrimSize);

  // Bottom scrim
  const botGrad = ctx.createLinearGradient(0, size - scrimSize, 0, size);
  botGrad.addColorStop(
    0,
    isLight ? "rgba(255, 255, 255, 0)" : "rgba(8, 10, 15, 0)",
  );
  botGrad.addColorStop(
    1,
    isLight ? "rgba(255, 255, 255, 0.88)" : "rgba(8, 10, 15, 0.88)",
  );
  ctx.fillStyle = botGrad;
  ctx.fillRect(0, size - scrimSize, size, scrimSize);

  // Left scrim for date ticks
  const leftScrimW = Math.round(110 * s);
  const leftGrad = ctx.createLinearGradient(0, 0, leftScrimW, 0);
  leftGrad.addColorStop(
    0,
    isLight ? "rgba(255, 255, 255, 0.60)" : "rgba(8, 10, 15, 0.60)",
  );
  leftGrad.addColorStop(
    1,
    isLight ? "rgba(255, 255, 255, 0)" : "rgba(8, 10, 15, 0)",
  );
  ctx.fillStyle = leftGrad;
  ctx.fillRect(0, 0, leftScrimW, size);

  // 4. Inward Axis Ticks & Labels (Crisp, Enlarged, Non-blurry)
  const tickLength = Math.round(10 * s);
  const tickFontSize = Math.round(15 * s);
  const tickColor = isLight ? "#0f172a" : "#f8fafc";
  const tickLineColor = isLight
    ? "rgba(0, 0, 0, 0.5)"
    : "rgba(255, 255, 255, 0.6)";

  // A. Top Axis: Hours (6h, 12h, 18h) pointing inwards — excluding corner 0h tick
  ctx.save();
  ctx.font = `400 ${tickFontSize}px ${MONO_FONT_FAMILY}`;
  ctx.fillStyle = tickColor;
  ctx.strokeStyle = tickLineColor;
  ctx.lineWidth = Math.max(1, Math.round(1.5 * s));
  ctx.textAlign = "center";
  ctx.textBaseline = "top";

  for (const hour of FINGERPRINT_HOUR_TICKS) {
    if (hour === 0) continue; // Skip corner 0h tick
    const x = Math.round(((hour + 0.5) * size) / hoursPerDay);

    ctx.beginPath();
    ctx.moveTo(x, 0);
    ctx.lineTo(x, tickLength);
    ctx.stroke();

    ctx.fillText(`${hour}h`, x, tickLength + Math.round(3 * s));
  }
  ctx.restore();

  // B. Left Axis: Day / Month / Year ticks pointing inwards
  if (nDays > 0) {
    let dayAxisTicks: { dayLocal: number; label: string }[] = [];

    if (!activeYearRange && allYears.length > 1) {
      // Multiple years window: Show ALL year ticks at the center of each year band
      dayAxisTicks = allYears.map((range) => ({
        dayLocal: Math.round((range.startDay + range.endDay) / 2),
        label: String(range.year),
      }));
    } else {
      // Single year window: Show month ticks across the year
      dayAxisTicks = dayIndexTicks(nDays, 6).map((offset) => ({
        dayLocal: offset,
        label: formatDayTick(baseDay + offset),
      }));
    }

    ctx.save();
    ctx.font = `400 ${tickFontSize}px ${MONO_FONT_FAMILY}`;
    ctx.fillStyle = tickColor;
    ctx.strokeStyle = tickLineColor;
    ctx.lineWidth = Math.max(1, Math.round(1.5 * s));
    ctx.textAlign = "left";
    ctx.textBaseline = "middle";

    for (let i = 0; i < dayAxisTicks.length; i++) {
      // When showing month ticks in a single year, skip i === 0 if near corner
      if (activeYearRange && i === 0) continue;

      const { dayLocal, label } = dayAxisTicks[i]!;
      const y = Math.round(
        (dayLocal / Math.max(1, nDays - 1)) * (size - Math.round(60 * s)) +
          Math.round(30 * s),
      );

      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(tickLength, y);
      ctx.stroke();

      ctx.fillText(label, tickLength + Math.round(5 * s), y);
    }
    ctx.restore();
  }

  // 5. Overlay Badges Styling Tokens (Frosted glass with high contrast)
  const badgeBg = isLight
    ? "rgba(255, 255, 255, 0.90)"
    : "rgba(10, 13, 20, 0.88)";
  const badgeBorder = isLight
    ? "rgba(0, 0, 0, 0.15)"
    : "rgba(255, 255, 255, 0.22)";
  const textPrimary = isLight ? "#0f172a" : "#ffffff";
  const textSecondary = isLight ? "#334155" : "rgba(255, 255, 255, 0.90)";

  // Layout positions: shifted right (x = 110px*s) to comfortably clear left ticks
  const topBadgeY = Math.round(48 * s);
  const leftInsetX = Math.round(110 * s);
  const rightMargin = Math.round(28 * s);
  const bottomMargin = Math.round(28 * s);

  // A. Top-Left: Data Source Provenance Badge
  const provFontSize = Math.round(20 * s);
  const provYearTag = activeYearRange ? ` · ${activeYearRange.year}` : "";
  const provText = `${prov.dataset} · ${prov.variable}${provYearTag} · ${prov.resolutionDeg}° grid`;

  ctx.save();
  ctx.font = `400 ${provFontSize}px ${SANS_FONT_FAMILY}`;
  const provTextW = ctx.measureText(provText).width;
  const provPadX = Math.round(20 * s);
  const provBadgeW = provTextW + provPadX * 2;
  const provBadgeH = Math.round(50 * s);
  const provBadgeR = Math.round(14 * s);

  ctx.fillStyle = badgeBg;
  ctx.strokeStyle = badgeBorder;
  ctx.lineWidth = Math.max(1, Math.round(1.5 * s));
  ctx.beginPath();
  ctx.roundRect(leftInsetX, topBadgeY, provBadgeW, provBadgeH, provBadgeR);
  ctx.fill();
  ctx.stroke();

  ctx.fillStyle = textPrimary;
  ctx.textAlign = "left";
  ctx.textBaseline = "middle";
  ctx.fillText(
    provText,
    leftInsetX + provPadX,
    topBadgeY + provBadgeH / 2,
  );
  ctx.restore();

  // B. Top-Right Corner: Watermark ("Generated by EarthPrints")
  const wmFontSize = Math.round(22 * s);
  ctx.save();
  ctx.font = `400 ${wmFontSize}px ${SANS_FONT_FAMILY}`;
  const wmTextW = ctx.measureText(watermarkText).width;
  const wmPadX = Math.round(22 * s);
  const wmBadgeW = wmTextW + wmPadX * 2;
  const wmBadgeH = Math.round(50 * s);
  const wmBadgeR = Math.round(14 * s);
  const wmBadgeLeft = size - rightMargin - wmBadgeW;

  ctx.fillStyle = badgeBg;
  ctx.strokeStyle = badgeBorder;
  ctx.lineWidth = Math.max(1, Math.round(1.5 * s));
  ctx.beginPath();
  ctx.roundRect(wmBadgeLeft, topBadgeY, wmBadgeW, wmBadgeH, wmBadgeR);
  ctx.fill();
  ctx.stroke();

  ctx.fillStyle = textPrimary;
  ctx.textAlign = "left";
  ctx.textBaseline = "middle";
  ctx.fillText(
    watermarkText,
    wmBadgeLeft + wmPadX,
    topBadgeY + wmBadgeH / 2,
  );
  ctx.restore();

  // C. Bottom-Left Corner: Origin Pixel Location Overlay
  const coordFontSize = Math.round(26 * s);
  const coordText = formatCardinalCoord(prov.cell.lat, prov.cell.lon);

  ctx.save();
  ctx.font = `400 ${coordFontSize}px ${MONO_FONT_FAMILY}`;
  const coordW = ctx.measureText(coordText).width;
  const coordPadX = Math.round(24 * s);
  const coordBadgeW = coordW + coordPadX * 2;
  const coordBadgeH = Math.round(56 * s);
  const coordBadgeR = Math.round(14 * s);
  const coordBadgeLeft = leftInsetX;
  const coordBadgeTop = size - bottomMargin - coordBadgeH;

  ctx.fillStyle = badgeBg;
  ctx.strokeStyle = badgeBorder;
  ctx.lineWidth = Math.max(1, Math.round(1.5 * s));
  ctx.beginPath();
  ctx.roundRect(
    coordBadgeLeft,
    coordBadgeTop,
    coordBadgeW,
    coordBadgeH,
    coordBadgeR,
  );
  ctx.fill();
  ctx.stroke();

  ctx.fillStyle = textPrimary;
  ctx.textAlign = "left";
  ctx.textBaseline = "middle";
  ctx.fillText(
    coordText,
    coordBadgeLeft + coordPadX,
    coordBadgeTop + coordBadgeH / 2,
  );
  ctx.restore();

  // D. Bottom-Right Corner: Diverging Colorbar Legend
  const legendFontSize = Math.round(20 * s);
  const minLabel = formatSeriesValue(-absMax);
  const maxLabel = `${formatSeriesValue(absMax)}${units ? ` ${units}` : ""}`;
  const legendStops = fingerprintLegendStops(isLight);

  ctx.save();
  ctx.font = `400 ${legendFontSize}px ${MONO_FONT_FAMILY}`;
  const minW = ctx.measureText(minLabel).width;
  const maxW = ctx.measureText(maxLabel).width;
  const barW = Math.round(140 * s);
  const barH = Math.round(12 * s);
  const gap = Math.round(12 * s);

  const legendPadX = Math.round(22 * s);
  const legendContentW = minW + gap + barW + gap + maxW;
  const legendBadgeW = legendContentW + legendPadX * 2;
  const legendBadgeH = Math.round(56 * s);
  const legendBadgeR = Math.round(14 * s);
  const legendBadgeLeft = size - rightMargin - legendBadgeW;
  const legendBadgeTop = size - bottomMargin - legendBadgeH;

  ctx.fillStyle = badgeBg;
  ctx.strokeStyle = badgeBorder;
  ctx.lineWidth = Math.max(1, Math.round(1.5 * s));
  ctx.beginPath();
  ctx.roundRect(
    legendBadgeLeft,
    legendBadgeTop,
    legendBadgeW,
    legendBadgeH,
    legendBadgeR,
  );
  ctx.fill();
  ctx.stroke();

  const legendMiddleY = legendBadgeTop + legendBadgeH / 2;

  // Min label
  ctx.fillStyle = textSecondary;
  ctx.textAlign = "left";
  ctx.textBaseline = "middle";
  ctx.fillText(minLabel, legendBadgeLeft + legendPadX, legendMiddleY);

  // Gradient ramp bar
  const rampLeft = legendBadgeLeft + legendPadX + minW + gap;
  const ramp = ctx.createLinearGradient(rampLeft, 0, rampLeft + barW, 0);
  ramp.addColorStop(0, legendStops.uptake);
  ramp.addColorStop(0.5, legendStops.mid);
  ramp.addColorStop(1, legendStops.release);

  ctx.fillStyle = ramp;
  ctx.beginPath();
  ctx.roundRect(rampLeft, legendMiddleY - barH / 2, barW, barH, barH / 2);
  ctx.fill();

  // Max label
  ctx.fillStyle = textSecondary;
  ctx.textAlign = "left";
  ctx.textBaseline = "middle";
  ctx.fillText(maxLabel, rampLeft + barW + gap, legendMiddleY);

  ctx.restore();

  return canvas;
}

/**
 * Builds captured image asset of the square vertical fingerprint logo.
 */
export function buildSquareFingerprintImage(
  options: SquareFingerprintOptions,
): CapturedImage {
  const canvas = buildSquareFingerprintCanvas(options);
  return {
    dataUrl: canvas.toDataURL("image/png"),
    width: canvas.width,
    height: canvas.height,
  };
}
