import {
  fingerprintColorScale,
  fingerprintLegendStops,
  symmetricAbsMax,
  yearRangesInWindow,
  FINGERPRINT_HOUR_TICKS,
} from "@/lib/map/fingerprintScale";
import { formatSeriesValue } from "@/components/map/timeSeriesChartConfig";
import type { ExportProvenance } from "./provenance";
import { isoDate } from "./provenance";
import type { CapturedImage } from "./capture";

export type SquareLogoPreset = {
  id: string;
  label: string;
  size: number;
};

export const SQUARE_LOGO_PRESETS: readonly SquareLogoPreset[] = [
  { id: "sm", label: "Small (512 × 512)", size: 512 },
  { id: "md", label: "Medium (800 × 800)", size: 800 },
  { id: "lg", label: "Standard (1024 × 1024)", size: 1024 },
  { id: "xl", label: "High-Res (1200 × 1200)", size: 1200 },
  { id: "2xl", label: "Ultra (2048 × 2048)", size: 2048 },
] as const;

export const DEFAULT_SQUARE_LOGO_SIZE = 1024;

export type SquareFingerprintOptions = {
  values: Float32Array;
  prov: ExportProvenance;
  units?: string | null;
  absMax?: number;
  hoursPerDay?: number;
  size?: number;
  isLight?: boolean;
  watermarkText?: string;
};

function formatCardinalCoord(lat: number, lon: number): string {
  const latStr = `${Math.abs(lat).toFixed(3)}° ${lat >= 0 ? "N" : "S"}`;
  const lonStr = `${Math.abs(lon).toFixed(3)}° ${lon >= 0 ? "E" : "W"}`;
  return `${latStr}, ${lonStr}`;
}

/**
 * Builds a high-resolution, square (1:1) logo-like vertical fingerprint graphic.
 *
 * Layout features:
 * - Vertical orientation (X = 0-23 hours, Y = chronological days descending)
 * - Overlaid origin pixel geographic coordinates
 * - Dataset & temporal window metadata
 * - Sleek diverging colorbar legend
 * - "Generated by EarthPrints" watermark branding (without URL)
 */
export function buildSquareFingerprintCanvas({
  values,
  prov,
  units = prov.units,
  absMax = symmetricAbsMax(values),
  hoursPerDay = prov.hoursPerDay || 24,
  size = DEFAULT_SQUARE_LOGO_SIZE,
  isLight = false,
  watermarkText = "Generated by EarthPrints",
}: SquareFingerprintOptions): HTMLCanvasElement {
  const canvas = document.createElement("canvas");
  canvas.width = size;
  canvas.height = size;

  const ctx = canvas.getContext("2d");
  if (!ctx) {
    throw new Error("Could not create 2D canvas context");
  }

  const s = size / 1024; // base scale factor relative to 1024px
  const nDays = Math.floor(values.length / hoursPerDay);

  // --- Palette & Theme tokens ---
  const bg = isLight ? "#ffffff" : "#0c0d12";
  const cardBg = isLight ? "#f8fafc" : "#13161f";
  const borderCol = isLight ? "rgba(0, 0, 0, 0.08)" : "rgba(255, 255, 255, 0.1)";
  const plotBorderCol = isLight ? "rgba(0, 0, 0, 0.12)" : "rgba(255, 255, 255, 0.14)";
  const textPrimary = isLight ? "#0f172a" : "#f8fafc";
  const textSecondary = isLight ? "#475569" : "rgba(255, 255, 255, 0.75)";
  const textTertiary = isLight ? "#64748b" : "rgba(255, 255, 255, 0.45)";
  const accent = isLight ? "#006c66" : "#52d4c8";

  // 1. Background fill
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, size, size);

  // Subtle ambient radial glow behind the fingerprint in dark mode
  if (!isLight) {
    const radial = ctx.createRadialGradient(
      size / 2,
      size * 0.48,
      size * 0.1,
      size / 2,
      size * 0.48,
      size * 0.55,
    );
    radial.addColorStop(0, "rgba(82, 212, 200, 0.07)");
    radial.addColorStop(1, "rgba(82, 212, 200, 0)");
    ctx.fillStyle = radial;
    ctx.fillRect(0, 0, size, size);
  }

  // Outer container card
  const pad = Math.round(36 * s);
  const cardW = size - pad * 2;
  const cardH = size - pad * 2;
  const cardR = Math.round(24 * s);

  ctx.save();
  ctx.fillStyle = cardBg;
  ctx.strokeStyle = borderCol;
  ctx.lineWidth = Math.max(1, Math.round(1.5 * s));
  ctx.beginPath();
  ctx.roundRect(pad, pad, cardW, cardH, cardR);
  ctx.fill();
  ctx.stroke();
  ctx.restore();

  // 2. Header Section: Coordinates & Metadata
  const headerTop = pad + Math.round(28 * s);
  const headerLeft = pad + Math.round(32 * s);
  const headerRight = pad + cardW - Math.round(32 * s);

  // Origin Pixel Coordinates (Lat, Lon)
  ctx.fillStyle = textPrimary;
  ctx.font = `700 ${Math.round(28 * s)}px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace`;
  ctx.textAlign = "left";
  ctx.textBaseline = "top";
  const coordText = formatCardinalCoord(prov.cell.lat, prov.cell.lon);
  ctx.fillText(coordText, headerLeft, headerTop);

  // Subtitle / Dataset info
  ctx.fillStyle = textTertiary;
  ctx.font = `500 ${Math.round(14 * s)}px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif`;
  const subText = `${prov.dataset} · ${prov.variable} · ${prov.resolutionDeg}° grid`;
  ctx.fillText(subText, headerLeft, headerTop + Math.round(36 * s));

  // Date span on the right
  ctx.textAlign = "right";
  ctx.fillStyle = accent;
  ctx.font = `600 ${Math.round(15 * s)}px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace`;
  const dateSpanText = `${isoDate(prov.windowStart)} → ${isoDate(prov.windowEnd)}`;
  ctx.fillText(dateSpanText, headerRight, headerTop + Math.round(4 * s));

  // Days and hours tag
  ctx.fillStyle = textTertiary;
  ctx.font = `500 ${Math.round(13 * s)}px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace`;
  ctx.fillText(
    `${nDays.toLocaleString()} days × ${hoursPerDay}h`,
    headerRight,
    headerTop + Math.round(36 * s),
  );

  // 3. Center Section: Framed Vertical Fingerprint Heatmap
  const plotTop = headerTop + Math.round(76 * s);
  const plotBot = size - pad - Math.round(112 * s);
  const plotH = Math.max(1, plotBot - plotTop);

  // Keep the heatmap centered and well-proportioned
  const plotLeft = headerLeft;
  const plotW = Math.max(1, headerRight - headerLeft);
  const plotR = Math.round(12 * s);

  // Draw plot background & clip rounded rectangle
  ctx.save();
  ctx.beginPath();
  ctx.roundRect(plotLeft, plotTop, plotW, plotH, plotR);
  ctx.clip();

  // Background for missing cells
  ctx.fillStyle = isLight ? "#ecece9" : "#1a1d26";
  ctx.fillRect(plotLeft, plotTop, plotW, plotH);

  // Rasterize vertical fingerprint: X = hour (0 to 23), Y = day (0 to nDays-1)
  if (nDays > 0) {
    const scale = fingerprintColorScale(isLight);
    const colW = plotW / hoursPerDay;

    for (let py = 0; py < plotH; py++) {
      const dayLocal = Math.min(nDays - 1, Math.floor((py / plotH) * nDays));
      for (let hour = 0; hour < hoursPerDay; hour++) {
        const val = values[dayLocal * hoursPerDay + hour] as number;
        const color = scale(val, absMax);
        if (color === "transparent") continue;

        const x0 = plotLeft + Math.floor(hour * colW);
        const x1 = plotLeft + Math.floor((hour + 1) * colW);
        ctx.fillStyle = color;
        ctx.fillRect(x0, plotTop + py, Math.max(1, x1 - x0), 1);
      }
    }
  }

  ctx.restore();

  // Plot border overlay
  ctx.save();
  ctx.strokeStyle = plotBorderCol;
  ctx.lineWidth = Math.max(1, Math.round(1.5 * s));
  ctx.beginPath();
  ctx.roundRect(plotLeft, plotTop, plotW, plotH, plotR);
  ctx.stroke();
  ctx.restore();

  // Hour tick indicator overlay at top of plot
  ctx.save();
  ctx.font = `600 ${Math.round(11 * s)}px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace`;
  ctx.fillStyle = textTertiary;
  ctx.textAlign = "center";
  ctx.textBaseline = "bottom";
  for (const hour of FINGERPRINT_HOUR_TICKS) {
    const tickX = plotLeft + ((hour + 0.5) * plotW) / hoursPerDay;
    ctx.fillText(`${hour}h`, tickX, plotTop - Math.round(4 * s));
  }
  ctx.restore();

  // 4. Diverging Legend & Colorbar
  const legendTop = plotBot + Math.round(18 * s);
  const legendH = Math.round(10 * s);
  const legendStops = fingerprintLegendStops(isLight);

  ctx.font = `600 ${Math.round(12 * s)}px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace`;
  ctx.textBaseline = "middle";

  const minLabel = formatSeriesValue(-absMax);
  const maxLabel = `${formatSeriesValue(absMax)}${units ? ` ${units}` : ""}`;

  ctx.fillStyle = textSecondary;
  ctx.textAlign = "left";
  ctx.fillText(minLabel, plotLeft, legendTop + legendH / 2);
  const minW = ctx.measureText(minLabel).width;

  ctx.textAlign = "right";
  ctx.fillText(maxLabel, headerRight, legendTop + legendH / 2);
  const maxW = ctx.measureText(maxLabel).width;

  const barGap = Math.round(12 * s);
  const barLeft = plotLeft + minW + barGap;
  const barRight = headerRight - maxW - barGap;
  const barW = Math.max(1, barRight - barLeft);

  const ramp = ctx.createLinearGradient(barLeft, 0, barLeft + barW, 0);
  ramp.addColorStop(0, legendStops.uptake);
  ramp.addColorStop(0.5, legendStops.mid);
  ramp.addColorStop(1, legendStops.release);

  ctx.fillStyle = ramp;
  ctx.beginPath();
  ctx.roundRect(barLeft, legendTop, barW, legendH, legendH / 2);
  ctx.fill();

  // 5. Watermark Footer: "Generated by EarthPrints"
  const footerY = size - pad - Math.round(28 * s);

  // Draw brand accent pip / dot
  const pipR = Math.round(4.5 * s);
  const pipX = headerLeft + pipR;
  const pipY = footerY;

  ctx.fillStyle = accent;
  ctx.beginPath();
  ctx.arc(pipX, pipY, pipR, 0, Math.PI * 2);
  ctx.fill();

  // Watermark text
  ctx.textAlign = "left";
  ctx.textBaseline = "middle";
  ctx.fillStyle = textPrimary;
  ctx.font = `600 ${Math.round(15 * s)}px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif`;
  ctx.fillText(watermarkText, pipX + pipR + Math.round(10 * s), footerY);

  // Origin cell tag on bottom right
  ctx.textAlign = "right";
  ctx.fillStyle = textTertiary;
  ctx.font = `500 ${Math.round(12 * s)}px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace`;
  ctx.fillText(
    `Cell (${prov.cell.lonIndex}, ${prov.cell.latIndex})`,
    headerRight,
    footerY,
  );

  return canvas;
}

/**
 * Builds captured image asset of the square vertical fingerprint logo.
 */
export function buildSquareFingerprintImage(
  options: SquareFingerprintOptions,
): CapturedImage {
  const canvas = buildSquareFingerprintCanvas(options);
  return {
    dataUrl: canvas.toDataURL("image/png"),
    width: canvas.width,
    height: canvas.height,
  };
}
