import {
  fingerprintColorScale,
  fingerprintLegendStops,
  symmetricAbsMax,
  yearRangesInWindow,
  dayIndexTicks,
  formatDayTick,
  FINGERPRINT_HOUR_TICKS,
} from "@/lib/map/fingerprintScale";
import { formatSeriesValue } from "@/components/map/timeSeriesChartConfig";
import type { ExportProvenance } from "./provenance";
import type { CapturedImage } from "./capture";

export type SquareLogoPreset = {
  id: string;
  label: string;
  size: number;
};

export const SQUARE_LOGO_PRESETS: readonly SquareLogoPreset[] = [
  { id: "sm", label: "Small (512 × 512)", size: 512 },
  { id: "md", label: "Medium (800 × 800)", size: 800 },
  { id: "lg", label: "Standard (1024 × 1024)", size: 1024 },
  { id: "xl", label: "High-Res (1200 × 1200)", size: 1200 },
  { id: "2xl", label: "Ultra (2048 × 2048)", size: 2048 },
] as const;

export const DEFAULT_SQUARE_LOGO_SIZE = 1024;

export type SquareFingerprintOptions = {
  values: Float32Array;
  prov: ExportProvenance;
  units?: string | null;
  absMax?: number;
  hoursPerDay?: number;
  size?: number;
  isLight?: boolean;
  watermarkText?: string;
  selectedYear?: number | null;
};

function formatCardinalCoord(lat: number, lon: number): string {
  const latStr = `${Math.abs(lat).toFixed(3)}° ${lat >= 0 ? "N" : "S"}`;
  const lonStr = `${Math.abs(lon).toFixed(3)}° ${lon >= 0 ? "E" : "W"}`;
  return `${latStr}, ${lonStr}`;
}

const MONO_FONT_FAMILY =
  'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace';
const SANS_FONT_FAMILY =
  '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';

/**
 * Builds a high-resolution, full-bleed square (1:1) vertical fingerprint graphic.
 *
 * Layout features:
 * - Full-bleed vertical heatmap filling the entire square (0,0 to size,size)
 * - Optical font scaling to guarantee crispy, sharp text across all resolutions
 * - Inward axis ticks: all year ticks when multi-year; month ticks when single-year
 * - Top-Left: Data source provenance badge with ample top and left padding
 * - Top-Right: Watermark "Generated by EarthPrints"
 * - Bottom-Left: Overlaid Origin Pixel geographic coordinates
 * - Right Side: Overlaid Vertical Diverging Colorbar legend with min/max & units
 */
export function buildSquareFingerprintCanvas({
  values,
  prov,
  units = prov.units,
  absMax = symmetricAbsMax(values),
  hoursPerDay = prov.hoursPerDay || 24,
  size = DEFAULT_SQUARE_LOGO_SIZE,
  isLight = false,
  watermarkText = "Generated by EarthPrints",
  selectedYear = null,
}: SquareFingerprintOptions): HTMLCanvasElement {
  const canvas = document.createElement("canvas");
  canvas.width = size;
  canvas.height = size;

  const ctx = canvas.getContext("2d");
  if (!ctx) {
    throw new Error("Could not create 2D canvas context");
  }

  // Optical font scaling: ensures typography never drops below legible threshold (13px minimum) at 512px
  const s = size / 1024;
  const fontScale = Math.max(0.85, s);

  const standardFontSize = Math.round(15 * fontScale);
  const legendUnitFontSize = Math.round(11 * fontScale);
  const tickFontSize = Math.round(13 * fontScale);

  const nDaysFull = Math.floor(values.length / hoursPerDay);

  // Derive year ranges across the loaded record
  const allYears = yearRangesInWindow(prov.baseDay, nDaysFull);
  const activeYearRange =
    selectedYear !== null
      ? (allYears.find((r) => r.year === selectedYear) ?? null)
      : null;

  const dayLo = activeYearRange ? activeYearRange.startDay : 0;
  const dayHi = activeYearRange ? activeYearRange.endDay : nDaysFull - 1;
  const nDays = Math.max(1, dayHi - dayLo + 1);
  const baseDay = prov.baseDay + dayLo;

  // 1. Base background for transparent/missing gaps
  ctx.fillStyle = isLight ? "#ffffff" : "#0a0c10";
  ctx.fillRect(0, 0, size, size);

  // 2. Full-bleed Vertical Fingerprint Heatmap (X = hour 0..23, Y = day 0..nDays-1)
  if (nDays > 0) {
    const scale = fingerprintColorScale(isLight);
    const colW = size / hoursPerDay;

    // Crisp pixel block rendering
    ctx.imageSmoothingEnabled = false;

    for (let py = 0; py < size; py++) {
      const dayOffset = Math.min(nDays - 1, Math.floor((py / size) * nDays));
      const dayGlobal = dayLo + dayOffset;

      for (let hour = 0; hour < hoursPerDay; hour++) {
        const val = values[dayGlobal * hoursPerDay + hour] as number;
        const color = scale(val, absMax);
        if (color === "transparent") continue;

        const x0 = Math.floor(hour * colW);
        const x1 = Math.floor((hour + 1) * colW);
        ctx.fillStyle = color;
        ctx.fillRect(x0, py, Math.max(1, x1 - x0), 1);
      }
    }
  }

  // 3. Subtle Ambient Corner Scrim Gradients for contrast
  const scrimSize = Math.round(180 * s);

  // Top scrim
  const topGrad = ctx.createLinearGradient(0, 0, 0, scrimSize);
  topGrad.addColorStop(
    0,
    isLight ? "rgba(255, 255, 255, 0.82)" : "rgba(8, 10, 15, 0.82)",
  );
  topGrad.addColorStop(
    1,
    isLight ? "rgba(255, 255, 255, 0)" : "rgba(8, 10, 15, 0)",
  );
  ctx.fillStyle = topGrad;
  ctx.fillRect(0, 0, size, scrimSize);

  // Bottom scrim
  const botGrad = ctx.createLinearGradient(0, size - scrimSize, 0, size);
  botGrad.addColorStop(
    0,
    isLight ? "rgba(255, 255, 255, 0)" : "rgba(8, 10, 15, 0)",
  );
  botGrad.addColorStop(
    1,
    isLight ? "rgba(255, 255, 255, 0.88)" : "rgba(8, 10, 15, 0.88)",
  );
  ctx.fillStyle = botGrad;
  ctx.fillRect(0, size - scrimSize, size, scrimSize);

  // Left scrim for date ticks
  const leftScrimW = Math.round(100 * s);
  const leftGrad = ctx.createLinearGradient(0, 0, leftScrimW, 0);
  leftGrad.addColorStop(
    0,
    isLight ? "rgba(255, 255, 255, 0.60)" : "rgba(8, 10, 15, 0.60)",
  );
  leftGrad.addColorStop(
    1,
    isLight ? "rgba(255, 255, 255, 0)" : "rgba(8, 10, 15, 0)",
  );
  ctx.fillStyle = leftGrad;
  ctx.fillRect(0, 0, leftScrimW, size);

  // Right scrim for vertical colorbar
  const rightScrimW = Math.round(100 * s);
  const rightGrad = ctx.createLinearGradient(size - rightScrimW, 0, size, 0);
  rightGrad.addColorStop(
    0,
    isLight ? "rgba(255, 255, 255, 0)" : "rgba(8, 10, 15, 0)",
  );
  rightGrad.addColorStop(
    1,
    isLight ? "rgba(255, 255, 255, 0.60)" : "rgba(8, 10, 15, 0.60)",
  );
  ctx.fillStyle = rightGrad;
  ctx.fillRect(size - rightScrimW, 0, rightScrimW, size);

  // 4. Inward Axis Ticks & Labels (Pixel-snapped, Crisp text)
  const tickLength = Math.max(6, Math.round(8 * s));
  const tickColor = isLight ? "#0f172a" : "#f8fafc";
  const tickLineColor = isLight
    ? "rgba(0, 0, 0, 0.55)"
    : "rgba(255, 255, 255, 0.65)";

  // A. Top Axis: Hours (6h, 12h, 18h) pointing inwards — excluding corner 0h tick
  ctx.save();
  ctx.font = `400 ${tickFontSize}px ${MONO_FONT_FAMILY}`;
  ctx.fillStyle = tickColor;
  ctx.strokeStyle = tickLineColor;
  ctx.lineWidth = Math.max(1, Math.round(1.5 * s));
  ctx.textAlign = "center";
  ctx.textBaseline = "top";

  for (const hour of FINGERPRINT_HOUR_TICKS) {
    if (hour === 0) continue; // Skip corner 0h tick
    const x = Math.round(((hour + 0.5) * size) / hoursPerDay);

    ctx.beginPath();
    ctx.moveTo(x, 0);
    ctx.lineTo(x, tickLength);
    ctx.stroke();

    ctx.fillText(`${hour}h`, x, tickLength + 3);
  }
  ctx.restore();

  // B. Left Axis: Day / Month / Year ticks pointing inwards
  if (nDays > 0) {
    let dayAxisTicks: { dayLocal: number; label: string }[] = [];

    if (!activeYearRange && allYears.length > 1) {
      // Multiple years window: Show ALL year ticks at the center of each year band
      dayAxisTicks = allYears.map((range) => ({
        dayLocal: Math.round((range.startDay + range.endDay) / 2),
        label: String(range.year),
      }));
    } else {
      // Single year window: Show month ticks across the year
      dayAxisTicks = dayIndexTicks(nDays, 6).map((offset) => ({
        dayLocal: offset,
        label: formatDayTick(baseDay + offset),
      }));
    }

    ctx.save();
    ctx.font = `400 ${tickFontSize}px ${MONO_FONT_FAMILY}`;
    ctx.fillStyle = tickColor;
    ctx.strokeStyle = tickLineColor;
    ctx.lineWidth = Math.max(1, Math.round(1.5 * s));
    ctx.textAlign = "left";
    ctx.textBaseline = "middle";

    for (let i = 0; i < dayAxisTicks.length; i++) {
      if (activeYearRange && i === 0) continue;

      const { dayLocal, label } = dayAxisTicks[i]!;
      const y = Math.round(
        (dayLocal / Math.max(1, nDays - 1)) * (size - Math.round(50 * s)) +
          Math.round(25 * s),
      );

      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(tickLength, y);
      ctx.stroke();

      ctx.fillText(label, tickLength + 4, y);
    }
    ctx.restore();
  }

  // 5. Overlay Badges Styling Tokens (Solid high-contrast cards)
  const badgeBg = isLight
    ? "rgba(255, 255, 255, 0.94)"
    : "rgba(10, 13, 20, 0.92)";
  const badgeBorder = isLight
    ? "rgba(0, 0, 0, 0.16)"
    : "rgba(255, 255, 255, 0.24)";
  const textPrimary = isLight ? "#0f172a" : "#ffffff";
  const textSecondary = isLight ? "#334155" : "rgba(255, 255, 255, 0.92)";
  const textTertiary = isLight ? "#64748b" : "rgba(255, 255, 255, 0.70)";

  // Layout positions
  const topBadgeY = Math.max(28, Math.round(42 * s));
  const leftInsetX = Math.max(64, Math.round(95 * s));
  const rightMargin = Math.max(16, Math.round(24 * s));
  const bottomMargin = Math.max(16, Math.round(24 * s));

  // A. Top-Left: Data Source Provenance Badge
  const provYearTag = activeYearRange ? ` · ${activeYearRange.year}` : "";
  const provText = `${prov.dataset} · ${prov.variable}${provYearTag} · ${prov.resolutionDeg}° grid`;

  ctx.save();
  ctx.font = `400 ${standardFontSize}px ${SANS_FONT_FAMILY}`;
  const provTextW = ctx.measureText(provText).width;
  const provPadX = Math.max(12, Math.round(16 * s));
  const provBadgeW = Math.round(provTextW + provPadX * 2);
  const provBadgeH = Math.max(28, Math.round(36 * fontScale));
  const provBadgeR = Math.max(8, Math.round(10 * s));

  ctx.fillStyle = badgeBg;
  ctx.strokeStyle = badgeBorder;
  ctx.lineWidth = Math.max(1, Math.round(1.5 * s));
  ctx.beginPath();
  ctx.roundRect(leftInsetX, topBadgeY, provBadgeW, provBadgeH, provBadgeR);
  ctx.fill();
  ctx.stroke();

  ctx.fillStyle = textPrimary;
  ctx.textAlign = "left";
  ctx.textBaseline = "middle";
  ctx.fillText(
    provText,
    leftInsetX + provPadX,
    topBadgeY + provBadgeH / 2,
  );
  ctx.restore();

  // B. Top-Right Corner: Watermark ("Generated by EarthPrints")
  ctx.save();
  ctx.font = `400 ${standardFontSize}px ${SANS_FONT_FAMILY}`;
  const wmTextW = ctx.measureText(watermarkText).width;
  const wmPadX = Math.max(12, Math.round(16 * s));
  const wmBadgeW = Math.round(wmTextW + wmPadX * 2);
  const wmBadgeH = Math.max(28, Math.round(36 * fontScale));
  const wmBadgeR = Math.max(8, Math.round(10 * s));
  const wmBadgeLeft = size - rightMargin - wmBadgeW;

  ctx.fillStyle = badgeBg;
  ctx.strokeStyle = badgeBorder;
  ctx.lineWidth = Math.max(1, Math.round(1.5 * s));
  ctx.beginPath();
  ctx.roundRect(wmBadgeLeft, topBadgeY, wmBadgeW, wmBadgeH, wmBadgeR);
  ctx.fill();
  ctx.stroke();

  ctx.fillStyle = textPrimary;
  ctx.textAlign = "left";
  ctx.textBaseline = "middle";
  ctx.fillText(
    watermarkText,
    wmBadgeLeft + wmPadX,
    topBadgeY + wmBadgeH / 2,
  );
  ctx.restore();

  // C. Bottom-Left Corner: Origin Pixel Location Overlay
  const coordText = formatCardinalCoord(prov.cell.lat, prov.cell.lon);

  ctx.save();
  ctx.font = `400 ${standardFontSize}px ${MONO_FONT_FAMILY}`;
  const coordW = ctx.measureText(coordText).width;
  const coordPadX = Math.max(12, Math.round(16 * s));
  const coordBadgeW = Math.round(coordW + coordPadX * 2);
  const coordBadgeH = Math.max(28, Math.round(36 * fontScale));
  const coordBadgeR = Math.max(8, Math.round(10 * s));
  const coordBadgeLeft = leftInsetX;
  const coordBadgeTop = size - bottomMargin - coordBadgeH;

  ctx.fillStyle = badgeBg;
  ctx.strokeStyle = badgeBorder;
  ctx.lineWidth = Math.max(1, Math.round(1.5 * s));
  ctx.beginPath();
  ctx.roundRect(
    coordBadgeLeft,
    coordBadgeTop,
    coordBadgeW,
    coordBadgeH,
    coordBadgeR,
  );
  ctx.fill();
  ctx.stroke();

  ctx.fillStyle = textPrimary;
  ctx.textAlign = "left";
  ctx.textBaseline = "middle";
  ctx.fillText(
    coordText,
    coordBadgeLeft + coordPadX,
    coordBadgeTop + coordBadgeH / 2,
  );
  ctx.restore();

  // D. Right Side: Vertical Diverging Colorbar Legend
  const legendNumFontSize = standardFontSize;
  const maxLabel = `+${formatSeriesValue(absMax)}`;
  const minLabel = formatSeriesValue(-absMax);
  const unitLabel = units || "";
  const legendStops = fingerprintLegendStops(isLight);

  ctx.save();
  ctx.font = `400 ${legendNumFontSize}px ${MONO_FONT_FAMILY}`;
  const maxNumW = ctx.measureText(maxLabel).width;
  const minNumW = ctx.measureText(minLabel).width;
  ctx.font = `400 ${legendUnitFontSize}px ${MONO_FONT_FAMILY}`;
  const unitW = unitLabel ? ctx.measureText(unitLabel).width : 0;

  const contentW = Math.max(maxNumW, minNumW, unitW);
  const vPadX = Math.max(12, Math.round(14 * s));
  const vPadY = Math.max(10, Math.round(12 * s));
  const vBadgeW = Math.round(contentW + vPadX * 2);

  const unitH = unitLabel ? Math.round(14 * fontScale) : 0;
  const topNumH = Math.round(16 * fontScale);
  const botNumH = Math.round(16 * fontScale);
  const gap = Math.max(4, Math.round(6 * fontScale));

  const vBarW = Math.max(6, Math.round(8 * s));
  const vBarH = Math.max(70, Math.round(120 * s));

  // Compute total height with exact inner heights and top/bottom padding
  const vBadgeH = Math.round(
    vPadY * 2 +
      (unitLabel ? unitH + gap : 0) +
      topNumH +
      gap +
      vBarH +
      gap +
      botNumH,
  );
  const vBadgeR = Math.max(8, Math.round(12 * s));
  const vBadgeLeft = size - rightMargin - vBadgeW;
  const vBadgeTop = size - bottomMargin - vBadgeH;

  // Draw Vertical Badge Container
  ctx.fillStyle = badgeBg;
  ctx.strokeStyle = badgeBorder;
  ctx.lineWidth = Math.max(1, Math.round(1.5 * s));
  ctx.beginPath();
  ctx.roundRect(vBadgeLeft, vBadgeTop, vBadgeW, vBadgeH, vBadgeR);
  ctx.fill();
  ctx.stroke();

  const centerX = Math.round(vBadgeLeft + vBadgeW / 2);

  // 1. Top Unit Label
  let curY = vBadgeTop + vPadY;
  if (unitLabel) {
    ctx.fillStyle = textTertiary;
    ctx.font = `400 ${legendUnitFontSize}px ${MONO_FONT_FAMILY}`;
    ctx.textAlign = "center";
    ctx.textBaseline = "top";
    ctx.fillText(unitLabel, centerX, curY);
    curY += unitH + gap;
  }

  // 2. Top Number Label (+absMax / Release)
  ctx.fillStyle = textSecondary;
  ctx.font = `400 ${legendNumFontSize}px ${MONO_FONT_FAMILY}`;
  ctx.textAlign = "center";
  ctx.textBaseline = "top";
  ctx.fillText(maxLabel, centerX, curY);
  curY += topNumH + gap;

  // 3. Vertical Gradient Colorbar
  const barLeft = Math.round(centerX - vBarW / 2);
  const barTop = curY;
  const vRamp = ctx.createLinearGradient(0, barTop, 0, barTop + vBarH);
  vRamp.addColorStop(0, legendStops.release);
  vRamp.addColorStop(0.5, legendStops.mid);
  vRamp.addColorStop(1, legendStops.uptake);

  ctx.fillStyle = vRamp;
  ctx.beginPath();
  ctx.roundRect(barLeft, barTop, vBarW, vBarH, Math.round(vBarW / 2));
  ctx.fill();

  // 4. Bottom Number Label (-absMax / Uptake)
  const botNumY = barTop + vBarH + gap;
  ctx.fillStyle = textSecondary;
  ctx.font = `400 ${legendNumFontSize}px ${MONO_FONT_FAMILY}`;
  ctx.textAlign = "center";
  ctx.textBaseline = "top";
  ctx.fillText(minLabel, centerX, botNumY);

  ctx.restore();

  return canvas;
}

/**
 * Builds captured image asset of the square vertical fingerprint logo.
 */
export function buildSquareFingerprintImage(
  options: SquareFingerprintOptions,
): CapturedImage {
  const canvas = buildSquareFingerprintCanvas(options);
  return {
    dataUrl: canvas.toDataURL("image/png"),
    width: canvas.width,
    height: canvas.height,
  };
}
